version: '2'

services:

  redis:
    image: redis:4.0.11
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - elk

  jupyter-tutorial:
    build:
     context: ./dockerfile
     dockerfile: dockerfile-jupyter
    container_name: elk_jupyter
    depends_on:
      - redis
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./code:/home/jovyan/work
      - /etc/localtime:/etc/localtime
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch    

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:

  elk:
    driver: bridge
