# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.1.0



# Add your kibana plugins setup here

RUN /bin/kibana-plugin install x-pack
# Example: RUN kibana-plugin install <name|url>
