# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0

RUN /bin/elasticsearch-plugin install x-pack

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
